# name of your github action
name: CI

on:
  push:
    branches:
      - main
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_mac:
    runs-on: macOS-latest
    defaults:
      run:
        shell: bash
        working-directory: test-bdoink
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
    - uses: actions/setup-node@master
      with:
        node-version: 12.14
    - name: see directory
      run: ls
    - name: install
      run: yarn install
    - name: build
      run: yarn electron:build --mac
    - name: see dist directory
      run: ls
      working-directory: test-bdoink/dist_electron

  build_on_win:
    runs-on: windows-2016
    defaults:
      run:
        shell: powershell
        working-directory: test-bdoink
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
    - uses: actions/setup-node@master
      with:
        node-version: 12.14
    - name: see directory
      run: ls
    - name: install
      run: yarn install
    - name: build
      run: yarn electron:build --win
    - name: see dist directory
      run: ls
      working-directory: test-bdoink/dist_electron
